### GENERAL SETTINGS ###

# Site settings
title: Kristi Witts
description: "Portfolio for southern California based web designer & developer, Kristi Witts"
analytics: UA-65704121-1
baseurl: "" #important: start with /
url: "http://dev.kristiwitts.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#01A2A6" #"#F70031"
  primary_rgb: "1,162,166" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#2F2933" #"#33004D"
  link: "#01A2A6"
  link_hover: "#29D9C2"
  footer_heading: "#FFFFA6"
  footer_content: "#ACA9AD"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/kristibeckart
  - title: twitter
    url: https://twitter.com/kristiwitts
  - title: instagram
    url: https://instagram.com/meatball777/
  - title: linkedin
    url: https://www.linkedin.com/in/kristiwitts
  - title: github
    url: https://github.com/kwitts

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: kristi@kristiwitts.com
tel: 602-538-1225


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I am a web designer & developer in Southern California with a focus on clean, mobile-first design and user-friendly web experiences."
